# EBA3510 Machine learning with Python

## Introduction
In this course, we will embark on an exciting journey into the realm of machine learning and data science. Machine learning, a subset of AI, empowers computers to learn from data and make predictions or decisions without explicit programming.

Throughout this course, we will leverage the power of Python, the most popular language for machine learning. Libraries such as scikit-learn provides a rich set of tools for data preprocessing, model building, evaluation, and much more. 

This course will equip you with the foundational knowledge and practical skills needed to tackle real-world problems involving data analysis, classification, and regression.

## Learning outcomes - Knowledge
* Basic concepts of machine learning and exploratory data analysis.
* Definition, interpretation, and properties of some of the most popular machine learning methods.
* Understanding of workflows in data science.

## Learning outcomes - Skills
* Applying Python libraries for loading, cleaning, and exploration of data.
* Fitting a variety of important machine learning models in Python and interpret the results.
* Presenting data analyses professionally using Quarto.

## General competence
During the course, students will also improve their general programming and presentation skills, and practice working in teams.

## Course content
* Loading, cleaning, and exploration of data.
* Quarto and Jupyter notebooks for presentation of analyses.
* Fitting of basic classifiers.
* Run and make informed choices among linear regression.
* Interpret the coefficients of regression models along with their p-values.
* Splitting data into test and training sets.
* Construction estimator pipelines, including data loading, preprocessing, fitting, and model evaluation.
* Perform regularized regression such as ridge and lasso.
* Usage of non-linear features such as polynomials and splines.
* Using principal component analysis in conjunction with regression or classification methods.
* Make informed choices between different models using cross-validation.
* Theory of model evaluation.

## Learning process and requirements to students
The course will be a combination of lectures and tutorials. Please note that while attendance is not compulsory in all courses, it is the student’s own responsibility to obtain any information provided in class that is not included on itslearning or in the text book.

## Curriculum
- James et al. (2023) An Introduction to Statistical Learning with Applications in Python

## Exam

## Keep


### Problems
I don't want to spend too much time on this stuff.

1. Non-linearity of the response-predictor relationships
  * Residual plots.
3. Non-constant variance of error terms
  * Residual plots
6. Collinearity
  * Plot and correlation matrix.
  * Computational results.
4. Outliers
  * Mention, but don't discuss the plots.
2. Correlation of error terms
  * Do not talk about.
5. High-leverage points
  * Do not talk about.

## On the $F$-test
1. 