project:
  type: book
  output-dir: docs

book:
  title: "Data science with `sklearn`"
  author: "Jonas Moss"
  date: "02.05.2024"
  search: false
  repo-url: https://github.com/bi-ds/EBA-3500/
  sidebar:
    style: floating
  chapters:
    - index.qmd
    - misc/sklearn.qmd
    - misc/plan.qmd
    - misc/python-tips.qmd
    - misc/on-exam.qmd
    - part: Curriculum and exercises
      chapters:
        - curriculum/lecture01.qmd
        - curriculum/lecture02.qmd
        - curriculum/lecture03.qmd
        - curriculum/lecture04.qmd
        - curriculum/lecture05.qmd
        - curriculum/lecture06.qmd
        - curriculum/lecture07.qmd
        - curriculum/lecture08.qmd
        - curriculum/lecture09.qmd
        - curriculum/lecture10.qmd
        - curriculum/lecture11.qmd
        - curriculum/lecture12.qmd
        - curriculum/lecture13.qmd
        - curriculum/lecture14.qmd
    - part: Lectures notes
    - part: Solutions to custom exercises
      chapters: 
        - solutions/custom/lecture01.qmd
    - part: Solutions to applied exercises
      chapters:
        - solutions/applied/ex4.8.13.qmd
        - solutions/applied/ex4.8.14.qmd
        - solutions/applied/ex4.8.15.qmd
        - solutions/applied/ex4.8.16.qmd
        - solutions/applied/ex5.4.5.qmd
        - solutions/applied/ex5.4.6.qmd
        - solutions/applied/ex5.4.8.qmd
        - solutions/applied/ex5.4.9.qmd
        - solutions/applied/ex6.6.8.qmd
        - solutions/applied/ex6.6.9.qmd
        - solutions/applied/ex7.9.6.qmd
        - solutions/applied/ex7.9.10.qmd
    - part: Solutions to conceptual exercises
      chapters:
        - solutions/conceptual/ex2.qmd
        - solutions/conceptual/ex3.qmd
        - solutions/conceptual/ex4.qmd
        - solutions/conceptual/ex5.qmd
        - solutions/conceptual/ex6.qmd
        - solutions/conceptual/ex7.qmd
        - solutions/conceptual/ex8.qmd
        - solutions/conceptual/ex9.qmd
        

format:
  html:
    theme:
      light: sandstone
      dark: superhero
    highlight-style: atom-one

editor: source
execute:
  cache: true
  enabled: true
  output: true
  freeze: auto
jupyter: python3
