# Functions in `sklearn` {.unnumbered}


## Chapter 4

### 
Softmax function.

### 
Naive Bayes.

###
Gaussian Naive Bayes.

###
Logistic regression.

###
What is the difference between multiple logistic regression and multinomial logistic regression?

###
You have a classification problem with $K$ classes, $p$ features, and $n$ observations. How many parameters is estimated by LDA?

###
You have a classification problem with $K$ classes, $p$ features, and $n$ observations. How many parameters is estimated by QDA?

###
You have a classification problem with $K$ classes, $p$ features, and $n$ observations. How many parameters is estimated by Gaussian naive Bayes?

###
You have a classification problem with $K$ classes, $p$ features, and $n$ observations. How many parameters is estimated by logistic regression?

###
Linear discriminant analysis.

###
Quadratic discriminant analysis.

### 
Who invented linear discriminant analysis, and in which year?
---
Ronald Fisher in 1936

###
Who invented multinomial logistic regression, and in which year?
---
David Cox in 1966

###
Describe the confusion matrix.

###
Describe the ROC curve.

###
What is the AUC?

###
Which of LDA, QDA, Gaussian naive Bayes and logistic regression could generate the following the decision boundary?

###
Generative models for classification.